### ISSUE TITLE
Fatal error: os_wizio.h: No such file or directory

### ISSUE THREAD

**Issue by Humancell** [OLIMEX/NB-IoT#6]
Hello,

I'm just getting going, and when I attempted to build I got: .../framework-quectel/arduino/cores/bc66/interface.h:27:10: fatal error: os_wizio.h: No such file or directory

I followed the steps to install: https://github.com/OLIMEX/NB-IoT/blob/master/SOFTWARE/NB-IoT-DevKit-PlatformIO-installation.pdf

Everything went well up to the build.  Are there steps that are missing that would have installed the other files?  I just did a git clone of your repo ...

**Comment by DanKoloff** [comment]
Try using the master branch instead:

https://github.com/Wiz-IO/platform-quectel

It has configuration of the Olimex board as far as I can see here:

https://github.com/Wiz-IO/platform-quectel/tree/master/boards

Also make sure to install this driver since it allows higher baud rate:

https://github.com/OLIMEX/ch340-dkms
